# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, the formatter and the nixpkgs this
# resolves against are shared with every other repo published from the
# monorepo: the framework is nix-workspace, the Rust build is its modules/rust
# directory. Both are callable through one call, so what is particular to this
# project is all that is left to say.
{
  description = "Rust reimplementation of the Tangled Spindle CI runner with native Nix engine";

  inputs = {
    workspace.url = "git+https://tangled.org/overby.me/nix-workspace";
    rust = {
      url = "git+https://tangled.org/overby.me/nix-workspace?dir=modules/rust";
      inputs.workspace.follows = "workspace";
    };
  };

  outputs = inputs:
    inputs.workspace {
      inherit inputs;
      rust.pname = "tangled-spindle-nix-engine";
      nixosModules."tangled-spindle-nix-engine" = ./nixos-module.nix;
    };
}
